[package]
name = 'SeaInit'
version = '0.1.0'

[addresses]
sea = "0x1639d77dcc10235c91f135a0a59606df36e60fa67a7757783ffa87a84a390299"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-framework"
# rev = "563e2abff8fa997aec81abe48772af8a20731f76"
rev = "main"
