[package]
name = "Sea"
version = "0.1.0" # Per SemVer

[addresses]
sea = "0x393a63f47da7a757a252cb44fbab2afe602efe9d88e8ae84aac7db4949a9beb0"

# sea_spot = "0x5e8c5122bd2ce18e45912699613ab527697bf58556815c08ad5463092dd91990"
sea_spot = "0xb30051d81a4f9e0303c7c3a31eb1b86d9e7518a5e9845147e2c4f07f12dae7a4"

# Mock users for unit tests
user_1 = "0x1111"
user_2 = "0x2222"
user_3 = "0x3333"
user_4 = "0x4444"

[dependencies.SeaInit]
local = "./sea_init/"

[dependencies.SeaLP]
local = "./sea_lp/"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-framework"
# rev = "563e2abff8fa997aec81abe48772af8a20731f76"
rev = "main"

[dependencies.UQ64x64]
git = "https://github.com/pontem-network/UQ64x64.git"
rev = "v0.3.7"

[dependencies.U256]
git = "https://github.com/pontem-network/U256.git"
rev = "v0.3.8"
