[package]
name = 'SeaLP'
version = '0.1.0'

# this is the resource account
[addresses]
# sea_spot = "0xe9d0916444fee21d6cce8409823d9962a304db7889b2cbfd816a7c2561c631d6"
sea_spot = "0x4f7d2de5a2b9797a9c74f906ef405dfc9c417da12d7d7eeff782eeb1ec896d2b"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-framework"
# rev = "563e2abff8fa997aec81abe48772af8a20731f76"
rev = "main"
